### PR TITLE
Nested workflows, scatter, fixes for workflow output

### PR DESCRIPTION
**Pull request by chapmanb**
Adam;
Thanks so much for this converter. I've been working on extending it with the goal of converting bcbio CWL workflows into WDL output and have an in-progress script that uses cwltool for parsing and cwl2wdl for WDL output generation:

https://github.com/chapmanb/bcbio-nextgen/blob/master/scripts/utils/cwltool2wdl.py

During this process I've added in some fixes and improvements to cwl2wdl and was hoping to contribute these:
- Support for nested sub-workflows
- Allow scattering of tasks and sub-workflows
- Bugfix to ensure tasks get correctly output
- Bugfix to include outputs in workflow definitions
- Support the CWL `separate` argument for commandline creation

In general, it would be great to collaborate with you on this and contribute the script as well once it's finalized and tested. My goal is to be able to convert a subset of CWL to WDL, avoiding more complex things like the expression languages. I think this will be a useful place to define a minimal subset of functionality that can support both and hopefully build additional collaboration between the two communities.

Thanks again for this work and for looking at these changes.

### CODE REVIEW

**Comment by adamstruck** [comment]
Hi @chapmanb thanks for this contribution! 

I have a couple questions for you:
1. Was the CWL parser in this code base insufficient?  I do think your approach of using cwltool for parsing makes more sense going forward - I was just curious if you tried it. 
2. What schema version are the CWL docs you are working to convert? I was working off draft 3 and haven't had a chance to revisit this code base since the 1.0 schema was released. 

It would be great to collaborate on this project. Honestly, I just haven't had the bandwidth lately to tackle this on my own.  Perhaps it would be useful to schedule a call in the future to discuss a roadmap for this project to get to that minimal subset of conversion support you mentioned.  For example, one thing that I think would benefit a project like this is a robust test suite that reports on conversion coverage over the CWL spec. Let me know what you think.

Thanks again for the contribution!

**Comment by chapmanb** [comment]
Adam;
Thanks so much for looking at this. I am targeting v1.0 so didn't test your CWL parsers in the code base assuming that I'd need to update it for all of the changes since draft 3. I'm not really very good at writing parsers so decided from the start to go with cwltool. I believe cwltool will also read draft 3 cleanly although I'm not sure if all the bits in the cwltool2wdl.py script handle any differences.

Definitely happy to talk more about plans. My approach is to try and get enough functionality in place to have bcbio converted WDL run with Cromwell. Some discussion on the WDL side for that is here:

http://gatkforums.broadinstitute.org/wdl/discussion/8454/feedback-on-initial-version-of-bcbio-wdl-converted-from-cwl#latest

If I can get this going then I could write up the details about the minimal subset of WDL/CWL that works for conversion and it would be great to have tests that exercise all this. Let me know how all that sounds and I can definitely pass along more details once I get something working after the conversion. Thanks again.

**Comment by adamstruck** [comment]
Are you going to be at the GA4GH hackathon in Vancouver today?

**Comment by chapmanb** [comment]
Adam -- unfortunately not. I'm sad to be missing it.

**Pull request merged**
